import { Piece } from "@/types/piece";

export const PLACEHOLDER_PIECES: Piece[] = [
  {
    id: "014",
    n: "014",
    srcs: ["/assets/piece-cobalt.png"],
    title: "small cobalt mug",
    note: "a cobalt slip, dipped twice — caught a finger on the second dip and left it.",
    glaze: "cobalt slip · clear",
    dim: "11×9 cm",
    price: 148,
    state: "here",
    collections: [],
  },
  {
    id: "015",
    n: "015",
    srcs: ["/assets/piece-blush.png"],
    title: "blush mug",
    note: "hand built, dipped once. the colour came out softer than expected.",
    glaze: "blush matte",
    dim: "10×8 cm",
    price: 62,
    state: "here",
    collections: [],
  },
  {
    id: "016",
    n: "016",
    srcs: ["/assets/piece-pour.png"],
    title: "a cream pitcher",
    note: "for the slow morning. small enough to live on the counter.",
    glaze: "oat satin",
    dim: "14×11 cm",
    price: 128,
    state: "here",
    collections: [],
  },
  {
    id: "017",
    n: "017",
    srcs: ["/assets/piece-speckled.png"],
    title: "speckled cup",
    note: "iron-bearing clay; the speckles came out of the kiln, not the glaze.",
    glaze: "clear over iron",
    dim: "9×8 cm",
    price: 58,
    state: "here",
    collections: [],
  },
  {
    id: "018",
    n: "018",
    srcs: ["/assets/piece-tall.png"],
    title: "tall cream cylinder",
    note: "a vase, but I have been using mine for utensils.",
    glaze: "oat satin",
    dim: "20×9 cm",
    price: 94,
    state: "here",
    collections: [],
  },
  {
    id: "019",
    n: "019",
    srcs: ["/assets/piece-olive.png"],
    title: "olive serving bowl",
    note: "wide enough for one salad or two soups. food safe.",
    glaze: "olive ash",
    dim: "22×8 cm",
    price: 94,
    state: "here",
    collections: [],
  },
  {
    id: "020",
    n: "020",
    srcs: ["/assets/piece-cream.png"],
    title: "low pinch bowl",
    note: "pinched, not thrown. a small ridge on one side where my thumb sat.",
    glaze: "oat satin",
    dim: "12×5 cm",
    price: 72,
    state: "here",
    collections: [],
  },
  {
    id: "021",
    n: "021",
    srcs: ["/assets/piece-saucer.png"],
    title: "small saucer plate",
    note: "for a teacup, a candle, or a single fig.",
    glaze: "clear",
    dim: "14×2 cm",
    price: 36,
    state: "here",
    collections: [],
  },
  {
    id: "022",
    n: "022",
    srcs: ["/assets/piece-pair.png"],
    title: "two morning mugs",
    note: "sold as a pair. one is slightly taller — please pick favourites generously.",
    glaze: "oat + cobalt",
    dim: "10×8 cm",
    price: 110,
    state: "gone",
    collections: [],
  },
  {
    id: "023",
    n: "023",
    srcs: ["/assets/piece-blush.png"],
    title: "rosé tumbler",
    note: "no handle. holds about a glass of wine, depending on how you pour.",
    glaze: "blush matte",
    dim: "11×7 cm",
    price: 48,
    state: "here",
    collections: [],
  },
  {
    id: "024",
    n: "024",
    srcs: ["/assets/piece-cobalt.png"],
    title: "deep blue tea bowl",
    note: "wider than the mug, no handle — for the way you hold a bowl in cold weather.",
    glaze: "cobalt slip",
    dim: "8×11 cm",
    price: 78,
    state: "here",
    collections: [],
  },
  {
    id: "025",
    n: "025",
    srcs: ["/assets/piece-pour.png"],
    title: "short cream pitcher",
    note: "milk for two coffees, or a small bunch of cuttings.",
    glaze: "oat satin",
    dim: "11×10 cm",
    price: 92,
    state: "gone",
    collections: [],
  },
];
