import type { Metadata } from "next";
import "./globals.css";
import FloatingBall from "./_components/FloatingBall";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <FloatingBall />
        <div className="flex justify-center items-center h-screen radius-xl">
          {children}
        </div>
      </body>
    </html>
  );
}
